/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Toolkit;


/**
 *
 * @author Laboratorio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/icono.png"));
        setIconImage(icon);
        this.setSize(600, 600);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        admin.setBackground(java.awt.Color.WHITE);
        cocina.setBackground(java.awt.Color.WHITE);
        mesero.setBackground(java.awt.Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Meseros = new javax.swing.JFrame();
        admin = new javax.swing.JButton();
        cocina = new javax.swing.JButton();
        mesero = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante La Prosperidad");
        getContentPane().setLayout(null);

        admin.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        admin.setText("Administración");
        admin.setBorder(null);
        admin.setBorderPainted(false);
        getContentPane().add(admin);
        admin.setBounds(30, 260, 170, 60);

        cocina.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        cocina.setText("Cocina");
        cocina.setBorder(null);
        getContentPane().add(cocina);
        cocina.setBounds(30, 350, 170, 60);

        mesero.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        mesero.setText("Meseros");
        mesero.setBorder(null);
        getContentPane().add(mesero);
        mesero.setBounds(30, 440, 170, 60);

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principal.png"))); // NOI18N
        getContentPane().add(FONDO);
        FONDO.setBounds(0, -20, 600, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(3500);
                } catch (Exception e) {
                }
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JFrame Meseros;
    private javax.swing.JButton admin;
    private javax.swing.JButton cocina;
    private javax.swing.JButton mesero;
    // End of variables declaration//GEN-END:variables
}
